// The SDK version reported in request headers must track package.json. It used
// to be hard-coded in src/index.ts and drifted two minors behind the published
// package, so every request mis-reported which SDK hit the backend.
// src/version.ts is generated by the `prebuild` script; these tests are the
// guard that it stays in sync and that nobody re-introduces a literal.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { SDK_VERSION } from '../dist/version.js';

const readRepoFile = (relativePath) =>
  readFileSync(fileURLToPath(new URL(relativePath, import.meta.url)), 'utf8');

const pkg = JSON.parse(readRepoFile('../package.json'));

test('SDK_VERSION matches package.json', () => {
  assert.equal(SDK_VERSION, pkg.version);
});

test('SDK_VERSION is a semver string', () => {
  assert.match(SDK_VERSION, /^\d+\.\d+\.\d+(?:[-+].*)?$/);
});

test('client headers carry no hard-coded version literal', () => {
  const source = readRepoFile('../src/index.ts');
  assert.equal(
    /['"`]\d+\.\d+\.\d+['"`]/.test(source),
    false,
    'src/index.ts contains a literal version string; import SDK_VERSION instead',
  );
});
